
DELETE FROM ORG;

DELETE FROM PROPERTY;

DELETE FROM TASK;

DELETE FROM SUBS;

DELETE FROM SUBSITEM;

DELETE FROM CREDENTIAL;

DELETE FROM INVITATION;
DELETE FROM INVITATION@major;
DELETE FROM INVITATION@majorminor;

DELETE FROM ARTICLE;
DELETE FROM ARTICLE@sujet;
DELETE FROM ARTICLE@auteurs;

DELETE FROM AUTEUR;

DELETE FROM CHAT;
DELETE FROM CHAT@participants;

DELETE FROM SUJET;