CREATE TABLE IF NOT EXISTS "ZZSAFE" (
  "id" TEXT,
  "hp0" TEXT,
  "hr0" TEXT,
  "hct" TEXT,
  "lam" INTEGER,
	"data" BLOB,
PRIMARY KEY(id));
CREATE INDEX IF NOT EXISTS "ZZSAFE_hp0" ON "ZZSAFE" ( "hp0" );
CREATE INDEX IF NOT EXISTS "ZZSAFE_hr0" ON "ZZSAFE" ( "hr0" );
CREATE INDEX IF NOT EXISTS "ZZSAFE_hct" ON "ZZSAFE" ( "hct" ) WHERE "hct" != '';
CREATE INDEX IF NOT EXISTS "ZZSAFE_lam" ON "ZZSAFE" ( "lam" );

CREATE TABLE IF NOT EXISTS "ZZUSERS" (
  "key" TEXT,
  "v" INTEGER,
	"value" TEXT,
PRIMARY KEY(key));

CREATE TABLE IF NOT EXISTS "ZZSVCOPS" (
  "key" TEXT,
  "v" INTEGER,
	"value" TEXT,
PRIMARY KEY(key));

CREATE TABLE IF NOT EXISTS "ZZORGS" (
  "key" TEXT,
  "v" INTEGER,
	"value" TEXT,
PRIMARY KEY(key));
