CREATE TABLE IF NOT EXISTS "ZZSAFE" (
  "userId" TEXT,
  "llq" INTEGER,
	"data" BLOB,
PRIMARY KEY(userId));
CREATE INDEX IF NOT EXISTS "ZZSAFE_llq" ON "ZZSAFE" ( "llq" );

CREATE TABLE IF NOT EXISTS "ZZUSERS" (
  "userId" TEXT,
  "hshK" TEXT,
  "hsha1" TEXT,
  "hsha2" TEXT,
  "C" TEXT,
  "V" TEXT,
  "llq" INTEGER,
	"store" TEXT,
PRIMARY KEY(userId));
CREATE INDEX IF NOT EXISTS "ZZUSERS_hsha1" ON "ZZUSERS" ( "hsha1" );
CREATE INDEX IF NOT EXISTS "ZZUSERS_hsha2" ON "ZZUSERS" ( "hsha2" )
  WHERE hsha2 IS NOT NULL;
CREATE INDEX IF NOT EXISTS "ZZUSERS_llq" ON "ZZUSERS" ( "llq" );

CREATE TABLE IF NOT EXISTS "ZZSVCOPS" (
  "key" TEXT,
  "v" INTEGER,
	"value" TEXT,
PRIMARY KEY(key));

CREATE TABLE IF NOT EXISTS "ZZORGS" (
  "key" TEXT,
  "v" INTEGER,
	"value" TEXT,
PRIMARY KEY(key));

CREATE TABLE IF NOT EXISTS "ZZCASES" (
  "caseId" TEXT,
  "userId" TEXT,
  "v" INTEGER,
  "data" BLOB,
PRIMARY KEY(caseId));
CREATE INDEX IF NOT EXISTS "ZZCASES_userId" ON "ZZCASES" ( "userId" );
CREATE INDEX IF NOT EXISTS "ZZCASES_v" ON "ZZCASES" ( "v" );