CREATE TABLE IF NOT EXISTS "SINGLETONS" (
  "key" TEXT,
  "value" TEXT,
PRIMARY KEY(key));



CREATE TABLE IF NOT EXISTS "ADMIN$STATUS" (
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"data" BLOB,
PRIMARY KEY(pk));
CREATE INDEX IF NOT EXISTS "ADMIN$STATUS_v" ON "ADMIN$STATUS" ( "v" );
CREATE INDEX IF NOT EXISTS "ADMIN$STATUS_ttl" ON "ADMIN$STATUS" ( "ttl" ) WHERE "ttl" > 0;

CREATE TABLE IF NOT EXISTS "ADMIN$TASK" (
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"startTime" TEXT,
	"data" BLOB,
PRIMARY KEY(pk));
CREATE INDEX IF NOT EXISTS "ADMIN$TASK_v" ON "ADMIN$TASK" ( "v" );
CREATE INDEX IF NOT EXISTS "ADMIN$TASK_ttl" ON "ADMIN$TASK" ( "ttl" ) WHERE "ttl" > 0;
CREATE INDEX IF NOT EXISTS "ADMIN$TASK_startTime" ON "ADMIN$TASK" ( "startTime" );

CREATE TABLE IF NOT EXISTS "ADMIN$SUBS" (
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"data" BLOB,
PRIMARY KEY(pk));
CREATE INDEX IF NOT EXISTS "ADMIN$SUBS_v" ON "ADMIN$SUBS" ( "v" );
CREATE INDEX IF NOT EXISTS "ADMIN$SUBS_ttl" ON "ADMIN$SUBS" ( "ttl" ) WHERE "ttl" > 0;

CREATE TABLE IF NOT EXISTS "ADMIN$SUBSITEM" (
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"def" TEXT,
	"data" BLOB,
PRIMARY KEY(pk));
CREATE INDEX IF NOT EXISTS "ADMIN$SUBSITEM_v" ON "ADMIN$SUBSITEM" ( "v" );
CREATE INDEX IF NOT EXISTS "ADMIN$SUBSITEM_ttl" ON "ADMIN$SUBSITEM" ( "ttl" ) WHERE "ttl" > 0;
CREATE INDEX IF NOT EXISTS "ADMIN$SUBSITEM_def" ON "ADMIN$SUBSITEM" ( "def" );

CREATE TABLE IF NOT EXISTS "AS2$STATUS" (
  "org" TEXT,
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"data" BLOB,
PRIMARY KEY(org, pk));
CREATE INDEX IF NOT EXISTS "AS2$STATUS_org" ON "AS2$STATUS" ( "org" );
CREATE INDEX IF NOT EXISTS "AS2$STATUS_v" ON "AS2$STATUS" ( "v" );
CREATE INDEX IF NOT EXISTS "AS2$STATUS_ttl" ON "AS2$STATUS" ( "ttl" ) WHERE "ttl" > 0;

CREATE TABLE IF NOT EXISTS "AS2$CREDENTIAL" (
  "org" TEXT,
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"doc" TEXT,
	"data" BLOB,
PRIMARY KEY(org, pk));
CREATE INDEX IF NOT EXISTS "AS2$CREDENTIAL_org" ON "AS2$CREDENTIAL" ( "org" );
CREATE INDEX IF NOT EXISTS "AS2$CREDENTIAL_v" ON "AS2$CREDENTIAL" ( "v" );
CREATE INDEX IF NOT EXISTS "AS2$CREDENTIAL_ttl" ON "AS2$CREDENTIAL" ( "ttl" ) WHERE "ttl" > 0;
CREATE INDEX IF NOT EXISTS "AS2$CREDENTIAL_doc" ON "AS2$CREDENTIAL" ( "doc" );

CREATE TABLE IF NOT EXISTS "AS2$FORM" (
  "org" TEXT,
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"creds" TEXT,
	"data" BLOB,
PRIMARY KEY(org, pk));
CREATE INDEX IF NOT EXISTS "AS2$FORM_org" ON "AS2$FORM" ( "org" );
CREATE INDEX IF NOT EXISTS "AS2$FORM_v" ON "AS2$FORM" ( "v" );
CREATE INDEX IF NOT EXISTS "AS2$FORM_ttl" ON "AS2$FORM" ( "ttl" ) WHERE "ttl" > 0;
CREATE INDEX IF NOT EXISTS "AS2$FORM_creds" ON "AS2$FORM" ( "creds" );

CREATE TABLE IF NOT EXISTS "AS2$AUTEUR" (
  "org" TEXT,
  "pk" TEXT,
  "v" INTEGER,
  "ttl" INTEGER,
	"section" TEXT,
	"nom" TEXT,
	"data" BLOB,
PRIMARY KEY(org, pk));
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR_org" ON "AS2$AUTEUR" ( "org" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR_v" ON "AS2$AUTEUR" ( "v" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR_ttl" ON "AS2$AUTEUR" ( "ttl" ) WHERE "ttl" > 0;
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR_section" ON "AS2$AUTEUR" ( "section" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR_nom" ON "AS2$AUTEUR" ( "nom" );

CREATE TABLE IF NOT EXISTS "AS2$AUTEUR@section" (
  "org" TEXT,
  "pk" TEXT,
  "v" INTEGER,
  "col" TEXT,
  "ttl" INTEGER,
PRIMARY KEY(org, pk));
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR@section_org" ON "AS2$AUTEUR" ( "org" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR@section_v" ON "AS2$AUTEUR" ( "v" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR@section_col" ON "AS2$AUTEUR" ( "col" );
CREATE INDEX IF NOT EXISTS "AS2$AUTEUR@section_ttl" ON "AS2$AUTEUR" ( "ttl" )  WHERE "ttl" > 0;
